'\" t
.\"     Title: mate-session-inhibit
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 02/16/2024
.\"    Manual: User Commands
.\"    Source: mate-session
.\"  Language: English
.\"
.TH "MATE\-SESSION\-INHIB" "1" "" "mate-session" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
mate-session-inhibit \- inhibit mate\-session functionality
.SH "SYNOPSIS"
.HP \w'\fBmate\-session\-inhibit\fR\ 'u
\fBmate\-session\-inhibit\fR [OPTION...] {COMMAND}
.SH "DESCRIPTION"
.PP
\fBmate\-session\-inhibit\fR
can inhibit certain mate\-session functionality while executing the given COMMAND\&. To achieve this, it calls the Inhibit() method of the mate\-session D\-Bus API and creates an inhibitor\&. The inhibitor is automatically removed when mate\-session\-inhibit exits\&.
.PP
A typical use case is to prevent the session from going idle (and thus locking the screen) while a movie player is running\&.
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
print help and exit
.RE
.PP
\fB\-\-version\fR
.RS 4
print version information and exit
.RE
.PP
\fB\-\-app\-id\fR ID
.RS 4
The application id to use when calling the mate\-session Inhibit() method\&. If this option is not specified, "unknown" is used\&.
.RE
.PP
\fB\-\-reason\fR REASON
.RS 4
A human\-readable reason to pass along when calling the mate\-session Inhibit() method\&. If this option is not specified, "not specified" is used\&.
.RE
.PP
\fB\-\-inhibit\fR ARG
.RS 4
ARG specifies the things to inhibit, as a colon\-separated list\&. The possible values are logout, switch\-user, suspend, idle, automount\&. If this option is used more than once, the values are combined\&. If this option is not specified, "idle" is assumed\&.
.RE
.SH "SEE ALSO"
.PP
\fBsystemd-inhibit\fR(1)
